# Generated by Django 3.1 on 2020-08-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_card', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=50)),
                ('tel_number', models.CharField(max_length=20)),
                ('info', models.TextField()),
                ('training_type', models.CharField(choices=[('I', 'Individual'), ('G', 'Group'), ('B', 'BOTH')], max_length=1)),
            ],
        ),
    ]
