# Generated by Django 3.1 on 2020-08-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tel_number', models.CharField(max_length=20)),
                ('info', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='training_type',
        ),
        migrations.AddField(
            model_name='client',
            name='cl_type',
            field=models.CharField(choices=[('I', 'Individual'), ('G', 'Group'), ('B', 'BOTH')], default='G', max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_type', models.CharField(choices=[('A', 'Взрослая'), ('C', 'Детская')], max_length=1)),
                ('sport_type', models.CharField(choices=[('B', 'Классический бокс'), ('T', 'Тайский бокс'), ('W', 'Женская группа'), ('M', 'ММА')], max_length=1)),
                ('time', models.TimeField()),
                ('trener', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.trener')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(choices=[('M', 'Машерова 17/4'), ('S', 'Свердлова 23')], max_length=1)),
                ('tel_number', models.CharField(max_length=20)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.group')),
            ],
        ),
    ]
