# Generated by Django 3.1 on 2020-08-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20200807_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='trener',
            options={'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AddField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='client_group', to='billing.Group'),
        ),
        migrations.AddField(
            model_name='client',
            name='treners',
            field=models.ManyToManyField(blank=True, related_name='client_trener', to='billing.Trener'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(choices=[('Машерова 17/4', 'Машерова 17/4'), ('Свердлова 23', 'Свердлова 23')], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='member_card',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='gr_type',
            field=models.CharField(choices=[('A', 'Взрослая'), ('C', 'Детская')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='sport_type',
            field=models.CharField(choices=[('B', 'Классический бокс'), ('T', 'Тайский бокс'), ('W', 'Женская группа'), ('M', 'ММА')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='trener',
            name='info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='trener',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='trener',
            name='tel_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
