# Generated by Django 3.1 on 2020-08-21 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20200821_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cl_type',
            field=models.CharField(choices=[('I', 'Individual'), ('G', 'Group'), ('B', 'BOTH')], default='G', max_length=1, verbose_name='Тип клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='client',
            name='member_card',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Членская карта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='group',
            name='trener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.trener'),
        ),
    ]
