# Generated by Django 3.1 on 2020-08-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20200821_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cl_type',
            field=models.CharField(choices=[('I', 'Индивидуал'), ('G', 'В группе'), ('B', 'Смешанный')], default='G', max_length=1, verbose_name='Тип клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(blank=True, to='billing.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='client',
            name='treners',
            field=models.ManyToManyField(blank=True, to='billing.Trener', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.address', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='group',
            name='gr_type',
            field=models.CharField(choices=[('A', 'Взрослая'), ('C', 'Детская')], default='A', max_length=1, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='group',
            name='sport_type',
            field=models.CharField(choices=[('B', 'Классический бокс'), ('T', 'Тайский бокс'), ('W', 'Женская группа'), ('M', 'ММА')], default='T', max_length=1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='group',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='group',
            name='trener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.trener', verbose_name='Тренер'),
        ),
    ]
