# Generated by Django 3.1 on 2020-08-21 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20200821_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=60, verbose_name='Сумма')),
                ('payment_type', models.CharField(choices=[('G', 'В группу'), ('I', 'Индивидуально')], default='G', max_length=1, verbose_name='Тип оплаты')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата оплаты')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.client', verbose_name='Плательщик')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.group', verbose_name='Группа')),
                ('trener', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.trener', verbose_name='Тренер')),
            ],
        ),
    ]
