# Generated by Django 3.1 on 2020-08-21 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплаты'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='billing.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='trener',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='billing.trener', verbose_name='Тренер'),
        ),
    ]
