# Generated by Django 3.1 on 2020-08-21 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20200821_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='trener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.trener', verbose_name='Тренер'),
        ),
    ]
