# Generated by Django 3.1 on 2020-08-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20200821_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_to',
            field=models.CharField(choices=[('G', 'В группу'), ('I', 'Индивидуально')], default='G', max_length=1, verbose_name='Направление оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('O', 'Разовый платеж'), ('M', 'Месячный взнос')], default='M', max_length=1, verbose_name='Тип оплаты'),
        ),
    ]
