# Generated by Django 3.1 on 2020-09-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20200821_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='trener_part',
            field=models.FloatField(blank=True, null=True, verbose_name='Тренеру'),
        ),
    ]
