# Generated by Django 3.1 on 2020-09-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_payment_trener_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='trener',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='billing/media/treners', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='trener_part',
            field=models.FloatField(default=0, verbose_name='Тренеру'),
        ),
    ]
