# Generated by Django 3.1 on 2020-09-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_auto_20200915_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='schedule',
            field=models.CharField(blank=True, choices=[('uneven', 'пн. ср. пт.'), ('even', 'вт. чт. сб.')], max_length=6, null=True, verbose_name='Расписание'),
        ),
    ]
