# Generated by Django 3.1 on 2020-09-18 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_group_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['trener'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.client', verbose_name='Плательщик'),
        ),
        migrations.AlterField(
            model_name='trener',
            name='tel_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
